version: 2.1

orbs:
  stoplight: stoplight/cli@0.0.2

commands:
  cached-dependencies:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  install-and-test:
    description: >-
      Install everything required to run the test suite, then run it.
    steps:
      - checkout
      - cached-dependencies
      - run: yarn
      - run: sudo apt install libsecret-1-0
      - run:
          name: Build the code
          command: yarn run compile
      - run:
          name: Lint the code
          command: yarn run lint
      - run:
          name: Run node tests
          command: yarn run test

jobs:
  test-node-latest:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - install-and-test

  test-node-12:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - install-and-test

  test-node-10:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - install-and-test

workflows:
  commit:
    jobs:
      - test-node-latest
      - test-node-12
      - test-node-10
